apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: online-boutique-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
